package sql

import (
	"context"
	"fmt"
)

func (s *SQLStr) FindAll() ([]Op, error) {
	rows, err := s.db.QueryContext(context.Background(), (queryAll))
	if err != nil {
		return nil, err
	}
	OPS := make(OPS, 0)
	for rows.Next() {
		ops := Op{}
		if err := rows.Scan(&ops.Ref, &ops.Ean, &ops.Nome, &ops.Cor, &ops.Tamanho, &ops.Uni, &ops.Quanti, &ops.Ex1, &ops.Ex2, &ops.Ex20, &ops.Grupo); err != nil {
			fmt.Println(err, ops)
			continue
		}
		OPS = append(OPS, Op{
			Ref:     ops.Ref,
			Ean:     ops.Ean,
			Nome:    ops.Nome,
			Cor:     ops.Cor,
			Tamanho: ops.Tamanho,
			Uni:     ops.Uni,
			Quanti:  ops.Quanti,
			Ex1:     ops.Ex1,
			Ex2:     ops.Ex2,
			Ex20:    ops.Ex20,
			Grupo:   ops.Grupo,
		})
	}
	return OPS, nil
}

const queryAll = `SELECT 
TOP(100)LTRIM(RTRIM(A.PRODUTO)) REFERENCIA
, LTRIM(RTRIM(K.CODIGO_BARRA)) EAN13
, LTRIM(RTRIM(A.DESC_PRODUTO)) NOME
, LTRIM(RTRIM(D.DESC_COR)) COR
, LTRIM(RTRIM(C.TAMANHO)) TAMANHO
, 'PECA' UNIDADE
, G.QUANTIDADE QUANTIDADE
, LTRIM(RTRIM(F.CLIFOR)) EXTRA1
, LTRIM(RTRIM(A.GRIFFE)) EXTRA2
, LTRIM(RTRIM(E.ORDEM_PRODUCAO)) EXTRA20
, LTRIM(RTRIM(A.GRUPO_PRODUTO)) GRUPO
FROM PRODUCAO_ORDEM E
LEFT JOIN PRODUTOS A ON E.PRODUTO=A.PRODUTO
JOIN PRODUTO_CORES B ON A.PRODUTO=B.PRODUTO
JOIN W_PRODUTOS_TAMANHOS_ORDEM C ON A.GRADE=C.GRADE
JOIN CORES_BASICAS D ON B.COR=D.COR
LEFT JOIN (
  SELECT PRODUTO, COR_PRODUTO, TAMANHO, MAX(CODIGO_BARRA) CODIGO_BARRA
  FROM PRODUTOS_BARRA
  WHERE TIPO_COD_BAR=1
  GROUP BY PRODUTO, COR_PRODUTO, TAMANHO
) K ON A.PRODUTO=K.PRODUTO AND B.COR_PRODUTO=K.COR_PRODUTO AND C.ORDEM=K.TAMANHO
LEFT JOIN CADASTRO_CLI_FOR F ON A.FABRICANTE=F.NOME_CLIFOR
LEFT JOIN (
    select ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 1 TAMANHO, O1 QUANTIDADE from PRODUCAO_ORDEM_COR 
  UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 2 TAMANHO, O2 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 3 TAMANHO, O3 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 4 TAMANHO, O4 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 5 TAMANHO, O5 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 6 TAMANHO, O6 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 7 TAMANHO, O7 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 8 TAMANHO, O8 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 9 TAMANHO, O9 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 10 TAMANHO, O10 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 11 TAMANHO, O11 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 12 TAMANHO, O12 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 13 TAMANHO, O13 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 14 TAMANHO, O14 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 15 TAMANHO, O15 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 16 TAMANHO, O16 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 17 TAMANHO, O17 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 18 TAMANHO, O18 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 19 TAMANHO, O19 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 20 TAMANHO, O20 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 21 TAMANHO, O21 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 22 TAMANHO, O22 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 23 TAMANHO, O23 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 24 TAMANHO, O24 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 25 TAMANHO, O25 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 26 TAMANHO, O26 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 27 TAMANHO, O27 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 28 TAMANHO, O28 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 29 TAMANHO, O29 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 30 TAMANHO, O30 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 31 TAMANHO, O31 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 32 TAMANHO, O32 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 33 TAMANHO, O33 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 34 TAMANHO, O34 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 35 TAMANHO, O35 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 36 TAMANHO, O36 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 37 TAMANHO, O37 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 38 TAMANHO, O38 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 39 TAMANHO, O39 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 40 TAMANHO, O40 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 41 TAMANHO, O41 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 42 TAMANHO, O42 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 43 TAMANHO, O43 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 44 TAMANHO, O44 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 45 TAMANHO, O45 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 46 TAMANHO, O46 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 47 TAMANHO, O47 QUANTIDADE from PRODUCAO_ORDEM_COR
UNION ALL SELECT ORDEM_PRODUCAO, PRODUTO, COR_PRODUTO, 48 TAMANHO, O48 QUANTIDADE from PRODUCAO_ORDEM_COR
    ) G ON E.ORDEM_PRODUCAO=G.ORDEM_PRODUCAO AND E.PRODUTO=G.PRODUTO AND B.COR_PRODUTO=G.COR_PRODUTO AND C.ORDEM=G.TAMANHO
WHERE A.INATIVO=0  AND G.QUANTIDADE>0
ORDER BY A.PRODUTO, D.DESC_COR, C.ORDEM
`
